version: '3'
services:
  app:
    build: 
     context: .
     dockerfile: Dockerfile
    container_name: azuredevops-notify
    ports:
      - 8080:8080
    networks:
      - bridge
    restart: always

networks:
  bridge:
    driver: bridge