version: '3'
services:
  app:
    build: .
    container_name: azure-devops-discord
    ports:
      - 8080:8080
    networks:
      - bridge
    restart: always

networks:
  bridge:
    driver: bridge