package main

import (
	models "discord-azure-integration/models"
	"time"
)

var fakeTime = time.Now()

var project = models.Project{
	ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
	Name:           "Project Doom",
	Description:    "Team Doom repository.",
	Url:            "https://doom.azure.com/",
	State:          "wellFormed",
	Revision:       123,
	Visibility:     "private",
	LastUpdateTime: fakeTime,
}

var fakePayloadCreatePR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers:          []models.Reviewers{},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadApprovedPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadRejectedPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        -10,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        -10,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadNeutralPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadWaitingPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        -5,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}
