package main

import (
	models "discord-azure-integration/models"
	"time"
)

var fakeTime = time.Now()

var project = models.Project{
	ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
	Name:           "Project Doom",
	Description:    "Team Doom repository.",
	Url:            "https://doom.azure.com/",
	State:          "wellFormed",
	Revision:       123,
	Visibility:     "private",
	LastUpdateTime: fakeTime,
}

var fakePayloadCreatePR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers:          []models.Reviewers{},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadApprovedPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadRejectedPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        -10,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        -10,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadNeutralPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadWaitingPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        -5,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadCompletedPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "completed",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadConflictPR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "conflicts",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "Conflicts",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadOrdinaryUpdatePR = models.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "doom",
	Message: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: models.Text{
		Text: "John Don created pull request 18111209 (branch > release) in repository",
	},
	Resource: models.Resource{
		Repository: models.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://doom.azure.com/",
			SshUrl:          "doom@vs-ssh.visualstudio.com:v3/project/repo",
			WebUrl:          "https://doom.azure.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: models.CreatedBy{
			DisplayName: "John Don",
			Url:         "https://johndon.com",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "john_don@doom.com.br",
			ImageUrl:    "http://johndon.com",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: models.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: models.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: models.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Committer: models.UserAuthor{
				Name:  "John Don",
				Email: "john_don@doom.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []models.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Jane Doe",
				UniqueName:  "Jane Doe",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Ali Gator",
				UniqueName:  "Ali Gator",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadPipelineUpdateSucceeded = models.AzurePipeline{
	SubscriptionId: "face7c3a-73ba-4ab8-a7f2-3d06da4b6b76",
	NotificationId: 2,
	ID:             "8d675cc3-96ee-4b3a-a7d3-0cbc1c548387",
	EventType:      "build.complete",
	PublisherId:    "tfs",
	Message: models.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	DetailedMessage: models.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	Resource: models.Resource{
		Links: models.Links{
			Self: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
			},
			Web: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_build/results?buildId=1809692",
			},
			SourceVersionDisplayUri: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/sources",
			},
			Timeline: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/Timeline",
			},
			Badge: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/status/7756",
			},
		},
		TriggerInfo: models.TriggerInfo{
			SourceBranch:      "refs/heads/homolog",
			SourceSha:         "b3ba205283e83517606e38602f76fadb3bdda522",
			Message:           "Merge branch 'feature/cetei-8368/suggestions-skynet-infra' into homolog",
			TriggerRepository: "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
		},
		ID:          1809692,
		BuildNumber: "20231212.2",
		Status:      "completed",
		Result:      "succeeded",
		QueueTime:   fakeTime,
		StartTime:   fakeTime,
		FinishTime:  fakeTime,
		Url:         "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
		Definition: models.Definition{
			ID:          7756,
			Name:        "empodera_workers-homolog",
			Url:         "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Definitions/7756?revision=2",
			Uri:         "vstfs:///Build/Definition/7756",
			Type:        "build",
			QueueStatus: "enabled",
			Revision:    2,
			Project: models.Project{
				ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				Name:           "Empodera",
				Description:    "Repositorio do time do Empodera.",
				Url:            "https://totvstfs.visualstudio.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				State:          "wellFormed",
				Revision:       3762,
				Visibility:     "private",
				LastUpdateTime: fakeTime,
			},
		},
		Project: models.Project{
			ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name:           "Empodera",
			Description:    "Repositorio do time do Empodera.",
			Url:            "https://totvstfs.visualstudio.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			State:          "wellFormed",
			Revision:       3762,
			Visibility:     "private",
			LastUpdateTime: fakeTime,
		},
		Uri: "vstfs:///Build/Build/1809692",
		RequestedFor: models.RequestedFor{
			DisplayName: "Iassam da Silva de Souza",
			Url:         "https://spsprodsbr1.vssps.visualstudio.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			Links: models.Links{
				Avatar: models.LinkHref{
					Href: "https://totvstfs.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
				},
			},
			ID:         "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName: "BRSSI0002@totvspartners.com.br",
			ImageUrl:   "https://totvstfs.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
		},
		Repository: models.Repository{
			ID:   "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
			Name: "empodera_workers",
			Url:  "https://totvstfs.visualstudio.com/Empodera/_git/empodera_workers",
		},
	},
	CreatedDate: fakeTime,
}

var fakePayloadPipelineUpdateFailed = models.AzurePipeline{
	SubscriptionId: "face7c3a-73ba-4ab8-a7f2-3d06da4b6b76",
	NotificationId: 2,
	ID:             "8d675cc3-96ee-4b3a-a7d3-0cbc1c548387",
	EventType:      "build.complete",
	PublisherId:    "tfs",
	Message: models.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	DetailedMessage: models.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	Resource: models.Resource{
		Links: models.Links{
			Self: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
			},
			Web: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_build/results?buildId=1809692",
			},
			SourceVersionDisplayUri: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/sources",
			},
			Timeline: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/Timeline",
			},
			Badge: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/status/7756",
			},
		},
		TriggerInfo: models.TriggerInfo{
			SourceBranch:      "refs/heads/homolog",
			SourceSha:         "b3ba205283e83517606e38602f76fadb3bdda522",
			Message:           "Merge branch 'feature/cetei-8368/suggestions-skynet-infra' into homolog",
			TriggerRepository: "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
		},
		ID:          1809692,
		BuildNumber: "20231212.2",
		Status:      "completed",
		Result:      "failed",
		QueueTime:   fakeTime,
		StartTime:   fakeTime,
		FinishTime:  fakeTime,
		Url:         "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
		Definition: models.Definition{
			ID:          7756,
			Name:        "empodera_workers-homolog",
			Url:         "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Definitions/7756?revision=2",
			Uri:         "vstfs:///Build/Definition/7756",
			Type:        "build",
			QueueStatus: "enabled",
			Revision:    2,
			Project: models.Project{
				ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				Name:           "Empodera",
				Description:    "Repositorio do time do Empodera.",
				Url:            "https://totvstfs.visualstudio.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				State:          "wellFormed",
				Revision:       3762,
				Visibility:     "private",
				LastUpdateTime: fakeTime,
			},
		},
		Project: models.Project{
			ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name:           "Empodera",
			Description:    "Repositorio do time do Empodera.",
			Url:            "https://totvstfs.visualstudio.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			State:          "wellFormed",
			Revision:       3762,
			Visibility:     "private",
			LastUpdateTime: fakeTime,
		},
		Uri: "vstfs:///Build/Build/1809692",
		RequestedFor: models.RequestedFor{
			DisplayName: "Iassam da Silva de Souza",
			Url:         "https://spsprodsbr1.vssps.visualstudio.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			Links: models.Links{
				Avatar: models.LinkHref{
					Href: "https://totvstfs.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
				},
			},
			ID:         "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName: "BRSSI0002@totvspartners.com.br",
			ImageUrl:   "https://totvstfs.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
		},
		Repository: models.Repository{
			ID:   "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
			Name: "empodera_workers",
			Url:  "https://totvstfs.visualstudio.com/Empodera/_git/empodera_workers",
		},
	},
	CreatedDate: fakeTime,
}

var fakePayloadPipelineUpdateStopped = models.AzurePipeline{
	SubscriptionId: "face7c3a-73ba-4ab8-a7f2-3d06da4b6b76",
	NotificationId: 2,
	ID:             "8d675cc3-96ee-4b3a-a7d3-0cbc1c548387",
	EventType:      "build.complete",
	PublisherId:    "tfs",
	Message: models.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	DetailedMessage: models.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	Resource: models.Resource{
		Links: models.Links{
			Self: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
			},
			Web: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_build/results?buildId=1809692",
			},
			SourceVersionDisplayUri: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/sources",
			},
			Timeline: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/Timeline",
			},
			Badge: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/status/7756",
			},
		},
		TriggerInfo: models.TriggerInfo{
			SourceBranch:      "refs/heads/homolog",
			SourceSha:         "b3ba205283e83517606e38602f76fadb3bdda522",
			Message:           "Merge branch 'feature/cetei-8368/suggestions-skynet-infra' into homolog",
			TriggerRepository: "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
		},
		ID:          1809692,
		BuildNumber: "20231212.2",
		Status:      "completed",
		Result:      "stopped",
		QueueTime:   fakeTime,
		StartTime:   fakeTime,
		FinishTime:  fakeTime,
		Url:         "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
		Definition: models.Definition{
			ID:          7756,
			Name:        "empodera_workers-homolog",
			Url:         "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Definitions/7756?revision=2",
			Uri:         "vstfs:///Build/Definition/7756",
			Type:        "build",
			QueueStatus: "enabled",
			Revision:    2,
			Project: models.Project{
				ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				Name:           "Empodera",
				Description:    "Repositorio do time do Empodera.",
				Url:            "https://totvstfs.visualstudio.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				State:          "wellFormed",
				Revision:       3762,
				Visibility:     "private",
				LastUpdateTime: fakeTime,
			},
		},
		Project: models.Project{
			ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name:           "Empodera",
			Description:    "Repositorio do time do Empodera.",
			Url:            "https://totvstfs.visualstudio.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			State:          "wellFormed",
			Revision:       3762,
			Visibility:     "private",
			LastUpdateTime: fakeTime,
		},
		Uri: "vstfs:///Build/Build/1809692",
		RequestedFor: models.RequestedFor{
			DisplayName: "Iassam da Silva de Souza",
			Url:         "https://spsprodsbr1.vssps.visualstudio.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			Links: models.Links{
				Avatar: models.LinkHref{
					Href: "https://totvstfs.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
				},
			},
			ID:         "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName: "BRSSI0002@totvspartners.com.br",
			ImageUrl:   "https://totvstfs.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
		},
		Repository: models.Repository{
			ID:   "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
			Name: "empodera_workers",
			Url:  "https://totvstfs.visualstudio.com/Empodera/_git/empodera_workers",
		},
	},
	CreatedDate: fakeTime,
}

var fakePayloadPipelineUpdateDefault = models.AzurePipeline{
	SubscriptionId: "face7c3a-73ba-4ab8-a7f2-3d06da4b6b76",
	NotificationId: 2,
	ID:             "8d675cc3-96ee-4b3a-a7d3-0cbc1c548387",
	EventType:      "build.complete",
	PublisherId:    "tfs",
	Message: models.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	DetailedMessage: models.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://totvstfs.visualstudio.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	Resource: models.Resource{
		Links: models.Links{
			Self: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
			},
			Web: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_build/results?buildId=1809692",
			},
			SourceVersionDisplayUri: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/sources",
			},
			Timeline: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/Timeline",
			},
			Badge: models.LinkHref{
				Href: "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/status/7756",
			},
		},
		TriggerInfo: models.TriggerInfo{
			SourceBranch:      "refs/heads/homolog",
			SourceSha:         "b3ba205283e83517606e38602f76fadb3bdda522",
			Message:           "Merge branch 'feature/cetei-8368/suggestions-skynet-infra' into homolog",
			TriggerRepository: "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
		},
		ID:          1809692,
		BuildNumber: "20231212.2",
		Status:      "completed",
		Result:      "default",
		QueueTime:   fakeTime,
		StartTime:   fakeTime,
		FinishTime:  fakeTime,
		Url:         "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
		Definition: models.Definition{
			ID:          7756,
			Name:        "empodera_workers-homolog",
			Url:         "https://totvstfs.visualstudio.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Definitions/7756?revision=2",
			Uri:         "vstfs:///Build/Definition/7756",
			Type:        "build",
			QueueStatus: "enabled",
			Revision:    2,
			Project: models.Project{
				ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				Name:           "Empodera",
				Description:    "Repositorio do time do Empodera.",
				Url:            "https://totvstfs.visualstudio.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				State:          "wellFormed",
				Revision:       3762,
				Visibility:     "private",
				LastUpdateTime: fakeTime,
			},
		},
		Project: models.Project{
			ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name:           "Empodera",
			Description:    "Repositorio do time do Empodera.",
			Url:            "https://totvstfs.visualstudio.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			State:          "wellFormed",
			Revision:       3762,
			Visibility:     "private",
			LastUpdateTime: fakeTime,
		},
		Uri: "vstfs:///Build/Build/1809692",
		RequestedFor: models.RequestedFor{
			DisplayName: "Iassam da Silva de Souza",
			Url:         "https://spsprodsbr1.vssps.visualstudio.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			Links: models.Links{
				Avatar: models.LinkHref{
					Href: "https://totvstfs.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
				},
			},
			ID:         "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName: "BRSSI0002@totvspartners.com.br",
			ImageUrl:   "https://totvstfs.visualstudio.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
		},
		Repository: models.Repository{
			ID:   "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
			Name: "empodera_workers",
			Url:  "https://totvstfs.visualstudio.com/Empodera/_git/empodera_workers",
		},
	},
	CreatedDate: fakeTime,
}
