package main

import (
	azdo "azuredevops-notify/internal/azuredevops"
	"time"
)

var fakeTime = time.Now().UTC()

var project = azdo.Project{
	ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
	Name:           "Sample Project",
	Description:    "Sample team repository.",
	Url:            "https://devops.example.com/",
	State:          "wellFormed",
	Revision:       123,
	Visibility:     "private",
	LastUpdateTime: fakeTime,
}

var fakePayloadCreatePR = azdo.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "tfs",
	Message: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	Resource: azdo.Resource{
		Repository: azdo.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://devops.example.com/",
			SshUrl:          "git@ssh.devops.example.com:v3/project/repo",
			WebUrl:          "https://devops.example.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: azdo.CreatedBy{
			DisplayName: "Alex Smith",
			Url:         "https://devops.example.com/",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "alex.smith@example.com",
			ImageUrl:    "https://devops.example.com/avatar.png",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: azdo.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: azdo.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: azdo.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Committer: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers:          []azdo.Reviewers{},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadApprovedPR = azdo.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "tfs",
	Message: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	Resource: azdo.Resource{
		Repository: azdo.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://devops.example.com/",
			SshUrl:          "git@ssh.devops.example.com:v3/project/repo",
			WebUrl:          "https://devops.example.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: azdo.CreatedBy{
			DisplayName: "Alex Smith",
			Url:         "https://devops.example.com/",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "alex.smith@example.com",
			ImageUrl:    "https://devops.example.com/avatar.png",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: azdo.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: azdo.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: azdo.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Committer: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []azdo.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Sarah Johnson",
				UniqueName:  "sarah.johnson@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Michael Brown",
				UniqueName:  "michael.brown@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadRejectedPR = azdo.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "tfs",
	Message: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	Resource: azdo.Resource{
		Repository: azdo.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://devops.example.com/",
			SshUrl:          "git@ssh.devops.example.com:v3/project/repo",
			WebUrl:          "https://devops.example.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: azdo.CreatedBy{
			DisplayName: "Alex Smith",
			Url:         "https://devops.example.com/",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "alex.smith@example.com",
			ImageUrl:    "https://devops.example.com/avatar.png",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: azdo.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: azdo.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: azdo.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Committer: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []azdo.Reviewers{
			{
				ID:          "fakeID",
				Vote:        -10,
				DisplayName: "Sarah Johnson",
				UniqueName:  "sarah.johnson@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        -10,
				DisplayName: "Michael Brown",
				UniqueName:  "michael.brown@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadNeutralPR = azdo.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "tfs",
	Message: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	Resource: azdo.Resource{
		Repository: azdo.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://devops.example.com/",
			SshUrl:          "git@ssh.devops.example.com:v3/project/repo",
			WebUrl:          "https://devops.example.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: azdo.CreatedBy{
			DisplayName: "Alex Smith",
			Url:         "https://devops.example.com/",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "alex.smith@example.com",
			ImageUrl:    "https://devops.example.com/avatar.png",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: azdo.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: azdo.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: azdo.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Committer: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []azdo.Reviewers{
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Sarah Johnson",
				UniqueName:  "sarah.johnson@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Michael Brown",
				UniqueName:  "michael.brown@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadWaitingPR = azdo.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "tfs",
	Message: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	Resource: azdo.Resource{
		Repository: azdo.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://devops.example.com/",
			SshUrl:          "git@ssh.devops.example.com:v3/project/repo",
			WebUrl:          "https://devops.example.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: azdo.CreatedBy{
			DisplayName: "Alex Smith",
			Url:         "https://devops.example.com/",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "alex.smith@example.com",
			ImageUrl:    "https://devops.example.com/avatar.png",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: azdo.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: azdo.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: azdo.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Committer: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []azdo.Reviewers{
			{
				ID:          "fakeID",
				Vote:        0,
				DisplayName: "Sarah Johnson",
				UniqueName:  "sarah.johnson@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        -5,
				DisplayName: "Michael Brown",
				UniqueName:  "michael.brown@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadCompletedPR = azdo.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "tfs",
	Message: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	Resource: azdo.Resource{
		Repository: azdo.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://devops.example.com/",
			SshUrl:          "git@ssh.devops.example.com:v3/project/repo",
			WebUrl:          "https://devops.example.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "completed",
		CreatedBy: azdo.CreatedBy{
			DisplayName: "Alex Smith",
			Url:         "https://devops.example.com/",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "alex.smith@example.com",
			ImageUrl:    "https://devops.example.com/avatar.png",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: azdo.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: azdo.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: azdo.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Committer: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []azdo.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Sarah Johnson",
				UniqueName:  "sarah.johnson@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Michael Brown",
				UniqueName:  "michael.brown@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadConflictPR = azdo.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "tfs",
	Message: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	Resource: azdo.Resource{
		Repository: azdo.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://devops.example.com/",
			SshUrl:          "git@ssh.devops.example.com:v3/project/repo",
			WebUrl:          "https://devops.example.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "conflicts",
		CreatedBy: azdo.CreatedBy{
			DisplayName: "Alex Smith",
			Url:         "https://devops.example.com/",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "alex.smith@example.com",
			ImageUrl:    "https://devops.example.com/avatar.png",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "Conflicts",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: azdo.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: azdo.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: azdo.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Committer: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []azdo.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Sarah Johnson",
				UniqueName:  "sarah.johnson@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Michael Brown",
				UniqueName:  "michael.brown@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadOrdinaryUpdatePR = azdo.AzureRequest{
	SubscriptionId: "2f5389a6-c75a-4048-8eba-33c0767d9ad6",
	NotificationId: 1094,
	ID:             "1c75aaf4-a8de-4748-835b-8bf7964ac0fa",
	EventType:      "git.pullrequest.created",
	PublisherId:    "tfs",
	Message: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	DetailedMessage: azdo.Text{
		Text: "Alex Smith created pull request 18111209 (branch > release) in repository",
	},
	Resource: azdo.Resource{
		Repository: azdo.Repository{
			ID:              "0f8a3f57-0bed-4451-86df-09d919e0d169",
			Name:            "repository_name",
			Url:             "https://azure.com/",
			Project:         project,
			Size:            132,
			RemoteUrl:       "https://devops.example.com/",
			SshUrl:          "git@ssh.devops.example.com:v3/project/repo",
			WebUrl:          "https://devops.example.com/",
			IsDisabled:      false,
			IsInMaintenance: false,
		},
		PullRequestId: 12333,
		CodeReviewId:  4123123,
		Status:        "active",
		CreatedBy: azdo.CreatedBy{
			DisplayName: "Alex Smith",
			Url:         "https://devops.example.com/",
			ID:          "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName:  "alex.smith@example.com",
			ImageUrl:    "https://devops.example.com/avatar.png",
		},
		CreationDate:  fakeTime,
		Title:         "feature > release",
		Description:   "PR Description",
		SourceRefName: "refs/heads/feature",
		TargetRefName: "refs/heads/release",
		MergeStatus:   "succeeded",
		IsDraft:       false,
		MergeID:       "9634d63f-a0ab-49de-8767-52e80ac18240",
		LastMergeSourceCommit: azdo.MergeCommit{
			CommitID: "d123faSsf2as1dfb234khb34kjb14",
			Url:      "https://",
		},
		LastMergeTargetCommit: azdo.MergeCommit{
			CommitID: "1h3hl41bl4hjb1l2j4hbl12j4hb123",
			Url:      "https://",
		},
		LastMergeCommit: azdo.MergeCommit{
			CommitID: "fds1234ufhXCsd2f76g9sdfCy1n3nh7bdc7208d3",
			Author: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Committer: azdo.UserAuthor{
				Name:  "Alex Smith",
				Email: "alex.smith@example.com",
				Date:  fakeTime,
			},
			Comment: "Merge pull request 1312312 from feature into release",
			Url:     "https://",
		},
		Reviewers: []azdo.Reviewers{
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Sarah Johnson",
				UniqueName:  "sarah.johnson@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
			{
				ID:          "fakeID",
				Vote:        10,
				DisplayName: "Michael Brown",
				UniqueName:  "michael.brown@example.com",
				Url:         "https://fakeurl.com",
				ReviewerUrl: "https://fakeurl.com",
				ImageUrl:    "https://fakeurl.com",
				IsContainer: false,
			},
		},
		Url:                "https://",
		SupportsIterations: true,
		ArtifactId:         "",
	},
	ResourceVersion: "1.0",
	CreatedDate:     fakeTime,
}

var fakePayloadPipelineUpdateSucceeded = azdo.AzurePipeline{
	SubscriptionId: "face7c3a-73ba-4ab8-a7f2-3d06da4b6b76",
	NotificationId: 2,
	ID:             "8d675cc3-96ee-4b3a-a7d3-0cbc1c548387",
	EventType:      "build.complete",
	PublisherId:    "tfs",
	Message: azdo.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	DetailedMessage: azdo.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	Resource: azdo.Resource{
		Links: azdo.Links{
			Self: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
			},
			Web: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_build/results?buildId=1809692",
			},
			SourceVersionDisplayUri: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/sources",
			},
			Timeline: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/Timeline",
			},
			Badge: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/status/7756",
			},
		},
		TriggerInfo: azdo.TriggerInfo{
			SourceBranch:      "refs/heads/staging",
			SourceSha:         "b3ba205283e83517606e38602f76fadb3bdda522",
			Message:           "Merge branch 'feature/add-new-feature' into staging",
			TriggerRepository: "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
		},
		ID:          1809692,
		BuildNumber: "20231212.2",
		Status:      "completed",
		Result:      "succeeded",
		QueueTime:   fakeTime,
		StartTime:   fakeTime,
		FinishTime:  fakeTime,
		Url:         "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
		Definition: azdo.Definition{
			ID:          7756,
			Name:        "sample-service-staging",
			Url:         "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Definitions/7756?revision=2",
			Uri:         "vstfs:///Build/Definition/7756",
			Type:        "build",
			QueueStatus: "enabled",
			Revision:    2,
			Project: azdo.Project{
				ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				Name:           "Sample Project",
				Description:    "Sample team repository.",
				Url:            "https://devops.example.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				State:          "wellFormed",
				Revision:       3762,
				Visibility:     "private",
				LastUpdateTime: fakeTime,
			},
		},
		Project: azdo.Project{
			ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name:           "Sample Project",
			Description:    "Sample team repository.",
			Url:            "https://devops.example.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			State:          "wellFormed",
			Revision:       3762,
			Visibility:     "private",
			LastUpdateTime: fakeTime,
		},
		Uri: "vstfs:///Build/Build/1809692",
		RequestedFor: azdo.RequestedFor{
			DisplayName: "David Martinez",
			Url:         "https://devops.example.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			Links: azdo.Links{
				Avatar: azdo.LinkHref{
					Href: "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
				},
			},
			ID:         "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName: "david.martinez@example.com",
			ImageUrl:   "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
		},
		Repository: azdo.Repository{
			ID:   "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
			Name: "sample-service",
			Url:  "https://devops.example.com/SampleProject/_git/sample-service",
		},
	},
	CreatedDate: fakeTime,
}

var fakePayloadPipelineUpdateFailed = azdo.AzurePipeline{
	SubscriptionId: "face7c3a-73ba-4ab8-a7f2-3d06da4b6b76",
	NotificationId: 2,
	ID:             "8d675cc3-96ee-4b3a-a7d3-0cbc1c548387",
	EventType:      "build.complete",
	PublisherId:    "tfs",
	Message: azdo.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	DetailedMessage: azdo.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	Resource: azdo.Resource{
		Links: azdo.Links{
			Self: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
			},
			Web: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_build/results?buildId=1809692",
			},
			SourceVersionDisplayUri: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/sources",
			},
			Timeline: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/Timeline",
			},
			Badge: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/status/7756",
			},
		},
		TriggerInfo: azdo.TriggerInfo{
			SourceBranch:      "refs/heads/staging",
			SourceSha:         "b3ba205283e83517606e38602f76fadb3bdda522",
			Message:           "Merge branch 'feature/add-new-feature' into staging",
			TriggerRepository: "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
		},
		ID:          1809692,
		BuildNumber: "20231212.2",
		Status:      "completed",
		Result:      "failed",
		QueueTime:   fakeTime,
		StartTime:   fakeTime,
		FinishTime:  fakeTime,
		Url:         "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
		Definition: azdo.Definition{
			ID:          7756,
			Name:        "sample-service-staging",
			Url:         "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Definitions/7756?revision=2",
			Uri:         "vstfs:///Build/Definition/7756",
			Type:        "build",
			QueueStatus: "enabled",
			Revision:    2,
			Project: azdo.Project{
				ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				Name:           "Sample Project",
				Description:    "Sample team repository.",
				Url:            "https://devops.example.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				State:          "wellFormed",
				Revision:       3762,
				Visibility:     "private",
				LastUpdateTime: fakeTime,
			},
		},
		Project: azdo.Project{
			ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name:           "Sample Project",
			Description:    "Sample team repository.",
			Url:            "https://devops.example.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			State:          "wellFormed",
			Revision:       3762,
			Visibility:     "private",
			LastUpdateTime: fakeTime,
		},
		Uri: "vstfs:///Build/Build/1809692",
		RequestedFor: azdo.RequestedFor{
			DisplayName: "David Martinez",
			Url:         "https://devops.example.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			Links: azdo.Links{
				Avatar: azdo.LinkHref{
					Href: "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
				},
			},
			ID:         "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName: "david.martinez@example.com",
			ImageUrl:   "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
		},
		Repository: azdo.Repository{
			ID:   "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
			Name: "sample-service",
			Url:  "https://devops.example.com/SampleProject/_git/sample-service",
		},
	},
	CreatedDate: fakeTime,
}

var fakePayloadPipelineUpdateStopped = azdo.AzurePipeline{
	SubscriptionId: "face7c3a-73ba-4ab8-a7f2-3d06da4b6b76",
	NotificationId: 2,
	ID:             "8d675cc3-96ee-4b3a-a7d3-0cbc1c548387",
	EventType:      "build.complete",
	PublisherId:    "tfs",
	Message: azdo.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	DetailedMessage: azdo.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	Resource: azdo.Resource{
		Links: azdo.Links{
			Self: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
			},
			Web: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_build/results?buildId=1809692",
			},
			SourceVersionDisplayUri: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/sources",
			},
			Timeline: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/Timeline",
			},
			Badge: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/status/7756",
			},
		},
		TriggerInfo: azdo.TriggerInfo{
			SourceBranch:      "refs/heads/staging",
			SourceSha:         "b3ba205283e83517606e38602f76fadb3bdda522",
			Message:           "Merge branch 'feature/add-new-feature' into staging",
			TriggerRepository: "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
		},
		ID:          1809692,
		BuildNumber: "20231212.2",
		Status:      "completed",
		Result:      "stopped",
		QueueTime:   fakeTime,
		StartTime:   fakeTime,
		FinishTime:  fakeTime,
		Url:         "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
		Definition: azdo.Definition{
			ID:          7756,
			Name:        "sample-service-staging",
			Url:         "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Definitions/7756?revision=2",
			Uri:         "vstfs:///Build/Definition/7756",
			Type:        "build",
			QueueStatus: "enabled",
			Revision:    2,
			Project: azdo.Project{
				ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				Name:           "Sample Project",
				Description:    "Sample team repository.",
				Url:            "https://devops.example.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				State:          "wellFormed",
				Revision:       3762,
				Visibility:     "private",
				LastUpdateTime: fakeTime,
			},
		},
		Project: azdo.Project{
			ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name:           "Sample Project",
			Description:    "Sample team repository.",
			Url:            "https://devops.example.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			State:          "wellFormed",
			Revision:       3762,
			Visibility:     "private",
			LastUpdateTime: fakeTime,
		},
		Uri: "vstfs:///Build/Build/1809692",
		RequestedFor: azdo.RequestedFor{
			DisplayName: "David Martinez",
			Url:         "https://devops.example.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			Links: azdo.Links{
				Avatar: azdo.LinkHref{
					Href: "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
				},
			},
			ID:         "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName: "david.martinez@example.com",
			ImageUrl:   "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
		},
		Repository: azdo.Repository{
			ID:   "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
			Name: "sample-service",
			Url:  "https://devops.example.com/SampleProject/_git/sample-service",
		},
	},
	CreatedDate: fakeTime,
}

var fakePayloadPipelineUpdateDefault = azdo.AzurePipeline{
	SubscriptionId: "face7c3a-73ba-4ab8-a7f2-3d06da4b6b76",
	NotificationId: 2,
	ID:             "8d675cc3-96ee-4b3a-a7d3-0cbc1c548387",
	EventType:      "build.complete",
	PublisherId:    "tfs",
	Message: azdo.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	DetailedMessage: azdo.Message{
		Text:     "Build 20231212.2 succeeded",
		Html:     "Build <a href=\"https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&amp;builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692\">20231212.2</a> succeeded",
		Markdown: "Build [20231212.2](https://devops.example.com/web/build.aspx?pcguid=9482681b-1f8d-43f3-a7fd-84a89ac10fc9&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f1809692) succeeded",
	},
	Resource: azdo.Resource{
		Links: azdo.Links{
			Self: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
			},
			Web: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_build/results?buildId=1809692",
			},
			SourceVersionDisplayUri: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/sources",
			},
			Timeline: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/builds/1809692/Timeline",
			},
			Badge: azdo.LinkHref{
				Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/status/7756",
			},
		},
		TriggerInfo: azdo.TriggerInfo{
			SourceBranch:      "refs/heads/staging",
			SourceSha:         "b3ba205283e83517606e38602f76fadb3bdda522",
			Message:           "Merge branch 'feature/add-new-feature' into staging",
			TriggerRepository: "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
		},
		ID:          1809692,
		BuildNumber: "20231212.2",
		Status:      "completed",
		Result:      "default",
		QueueTime:   fakeTime,
		StartTime:   fakeTime,
		FinishTime:  fakeTime,
		Url:         "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Builds/1809692",
		Definition: azdo.Definition{
			ID:          7756,
			Name:        "sample-service-staging",
			Url:         "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/build/Definitions/7756?revision=2",
			Uri:         "vstfs:///Build/Definition/7756",
			Type:        "build",
			QueueStatus: "enabled",
			Revision:    2,
			Project: azdo.Project{
				ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				Name:           "Sample Project",
				Description:    "Sample team repository.",
				Url:            "https://devops.example.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
				State:          "wellFormed",
				Revision:       3762,
				Visibility:     "private",
				LastUpdateTime: fakeTime,
			},
		},
		Project: azdo.Project{
			ID:             "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name:           "Sample Project",
			Description:    "Sample team repository.",
			Url:            "https://devops.example.com/_apis/projects/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			State:          "wellFormed",
			Revision:       3762,
			Visibility:     "private",
			LastUpdateTime: fakeTime,
		},
		Uri: "vstfs:///Build/Build/1809692",
		RequestedFor: azdo.RequestedFor{
			DisplayName: "David Martinez",
			Url:         "https://devops.example.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			Links: azdo.Links{
				Avatar: azdo.LinkHref{
					Href: "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
				},
			},
			ID:         "a4dd11b6-b7bc-64e7-8a8e-1617179bef68",
			UniqueName: "david.martinez@example.com",
			ImageUrl:   "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.YTRkZDExYjYtYjdiYy03NGU3LThhOGUtMTYxNzE3OWJlZjY4",
		},
		Repository: azdo.Repository{
			ID:   "7a7c38b3-ac94-4e1e-b47e-d746c762079a",
			Name: "sample-service",
			Url:  "https://devops.example.com/SampleProject/_git/sample-service",
		},
	},
	CreatedDate: fakeTime,
}

var fakePayloadReleaseSuccess = azdo.AzurePipeline{
	SubscriptionId: "a2346054-e9af-491c-9273-fe07c3bffa01",
	NotificationId: 1,
	ID:             "7ae37a82-9be5-4906-82fb-6a796ad95cac",
	EventType:      "ms.vss-release.deployment-completed-event",
	PublisherId:    "rm",
	Message: azdo.Message{
		Text:     "Deployment of release Release-62 on stage deploy staging server succeeded.",
		Html:     "Deployment on stage <a href='https://devops.example.com/SampleProject/_release?_a=environment-summary&definitionId=35&definitionEnvironmentId=67'>deploy staging server</a> succeeded.",
		Markdown: "Deployment on stage [deploy staging server](https://devops.example.com/SampleProject/_release?_a=environment-summary&definitionId=35&definitionEnvironmentId=67) succeeded.",
	},
	DetailedMessage: azdo.Message{
		Text:     "Deployment of release Release-62 on stage deploy staging server succeeded. Time to deploy: 00:03:07.",
		Html:     "Deployment on stage <a href='https://devops.example.com/SampleProject/_release?_a=environment-summary&definitionId=35&definitionEnvironmentId=67'>deploy staging server</a> succeeded. Time to deploy: 00:03:07.",
		Markdown: "Deployment on stage [deploy staging server](https://devops.example.com/SampleProject/_release?_a=environment-summary&definitionId=35&definitionEnvironmentId=67) succeeded. Time to deploy: 00:03:07.",
	},
	Resource: azdo.Resource{
		Environment: azdo.Environment{
			ID:         15999,
			ReleaseID:  7269,
			Name:       "deploy staging server",
			Status:     "succeeded",
			CreatedOn:  fakeTime,
			ModifiedOn: fakeTime,
			Release: azdo.Release{
				ID:   7269,
				Name: "Release-62",
				Url:  "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/Release/releases/7269",
				Links: azdo.Links{
					Web: azdo.LinkHref{
						Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_release?releaseId=7269&_a=release-summary",
					},
					Self: azdo.LinkHref{
						Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/Release/releases/7269",
					},
				},
			},
			ReleaseDefinition: azdo.Release{
				ID:   35,
				Name: "sample api staging",
				Url:  "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/Release/definitions/35",
				Links: azdo.Links{
					Web: azdo.LinkHref{
						Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_release?definitionId=35",
					},
					Self: azdo.LinkHref{
						Href: "https://devops.example.com/a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9/_apis/Release/definitions/35",
					},
				},
			},
			ReleaseCreatedBy: azdo.RequestedFor{
				DisplayName: "Emily Chen",
				Url:         "https://devops.example.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/0f5c62b4-a018-636c-a082-a76705f2f2cb",
				Links: azdo.Links{
					Avatar: azdo.LinkHref{
						Href: "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.MGY1YzYyYjQtYTAxOC03MzZjLWEwODItYTc2NzA1ZjJmMmNi",
					},
				},
				ID:         "0f5c62b4-a018-636c-a082-a76705f2f2cb",
				UniqueName: "emily.chen@example.com",
				ImageUrl:   "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.MGY1YzYyYjQtYTAxOC03MzZjLWEwODItYTc2NzA1ZjJmMmNi",
			},
			TriggerReason: "ReleaseStarted",
			TimeToDeploy:  3.1220666666666665,
		},
		Project: azdo.Project{
			ID:   "a133d6b5-dfbe-49b7-9a8f-d8cb27e3adc9",
			Name: "Sample Project",
		},
		Deployment: azdo.Deployment{
			ID:               10414,
			Reason:           "automated",
			DeploymentStatus: "succeeded",
			OperationStatus:  "Approved",
			RequestedBy: azdo.RequestedFor{
				DisplayName: "Microsoft.VisualStudio.Services.ReleaseManagement",
				ID:          "0000000d-0000-8888-8000-000000000000",
				UniqueName:  "0000000d-0000-8888-8000-000000000000@2c895908-04e0-4952-89fd-54b0046d6288",
			},
			RequestedFor: azdo.RequestedFor{
				DisplayName: "Emily Chen",
				Url:         "https://devops.example.com/Aecd9a5a6-03de-436d-acc4-a73f4c80ca8f/_apis/Identities/0f5c62b4-a018-636c-a082-a76705f2f2cb",
				Links: azdo.Links{
					Avatar: azdo.LinkHref{
						Href: "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.MGY1YzYyYjQtYTAxOC03MzZjLWEwODItYTc2NzA1ZjJmMmNi",
					},
				},
				ID:         "0f5c62b4-a018-636c-a082-a76705f2f2cb",
				UniqueName: "emily.chen@example.com",
				ImageUrl:   "https://devops.example.com/_apis/GraphProfile/MemberAvatars/aad.MGY1YzYyYjQtYTAxOC03MzZjLWEwODItYTc2NzA1ZjJmMmNi",
			},
			QueuedOn:    fakeTime,
			StartedOn:   fakeTime,
			CompletedOn: fakeTime,
		},
		StageName: "deploy staging server",
		AttemptId: 1,
		ID:        7269,
		Url:       "https://devops.example.com/SampleProject/_release?releaseId=7269&_a=release-summary",
	},
	CreatedDate: fakeTime,
}
